name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: "16"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install npm
      run: npm install npm
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install npm
      run: npm install -g npm
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - name: Install Dependencies
      run: npm install
    - name: Run Prettier
      run: npm run prettier
