name: End-to-end tests parallel

on: 
  push:
    branches:
      - main

jobs:
  cypress-run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: v20.14.0

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:api

  cypress-run-compatibilidade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: v20.14.0

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:compatibilidade

  cypress-run-funcional:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: v20.14.0

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:funcional

