name: End-to-end tests parallel

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [api, funcional]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: v20.14.0

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:${{ matrix.test-type }}

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.test-type }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.test-type }}
          path: cypress/videos
          if-no-files-found: ignore
